DASHSCOPE_API_KEY="YOUR_API_KEY_HERE"
TAVILY_API_KEY="YOUR_API_KEY_HERE"
LANGSMITH_API_KEY="YOUR_API_KEY_HERE"

skin_key = "YOUR_SKIN_KEY_HERE"
skin_secret = "YOUR_SKIN_SECRET_HERE"

password="YOUR_PASSWORD_HERE"
neo4j_name="neo4j"
project="YOUR_PROJECT_NAME"
